# Generated by Django 4.2.7 on 2026-04-06 10:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('spam', 'Spam'), ('promotion', 'Promotion'), ('otp', 'OTP'), ('important', 'Important'), ('personal', 'Personal')], max_length=20)),
                ('confidence', models.FloatField()),
                ('is_phishing', models.BooleanField(default=False)),
                ('phishing_score', models.FloatField(default=0.0)),
                ('message_hash', models.CharField(max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('language', models.CharField(default='en', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_category', models.CharField(max_length=20)),
                ('corrected_category', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sms_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api.smslog')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['-timestamp'], name='api_smslog_timesta_6c9aca_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['category'], name='api_smslog_categor_380f7f_idx'),
        ),
    ]
