# Generated by Django 4.2.7 on 2026-04-06 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_messages', models.IntegerField(default=0)),
                ('spam_count', models.IntegerField(default=0)),
                ('phishing_count', models.IntegerField(default=0)),
                ('avg_confidence', models.FloatField(default=0.0)),
                ('unique_senders', models.IntegerField(default=0)),
                ('high_risk_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('training_samples', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SenderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_hash', models.CharField(max_length=64, unique=True)),
                ('total_messages', models.IntegerField(default=0)),
                ('spam_count', models.IntegerField(default=0)),
                ('legitimate_count', models.IntegerField(default=0)),
                ('reputation_score', models.FloatField(default=0.5)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='ThreatPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(max_length=50)),
                ('pattern_text', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('frequency', models.IntegerField(default=1)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.AddField(
            model_name='smslog',
            name='has_financial_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smslog',
            name='has_phone_numbers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smslog',
            name='has_urls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smslog',
            name='message_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smslog',
            name='risk_level',
            field=models.CharField(choices=[('safe', 'Safe'), ('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical')], default='safe', max_length=20),
        ),
        migrations.AddField(
            model_name='smslog',
            name='sender_reputation',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='smslog',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='smslog',
            name='urgency_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='feedback_quality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['risk_level'], name='api_smslog_risk_le_5623c8_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['is_phishing'], name='api_smslog_is_phis_c2a0a6_idx'),
        ),
    ]
