# Generated by Django 4.2.7 on 2026-04-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_analyticssnapshot_modelperformance_senderprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='message_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
