# Generated by Django 4.2.7 on 2026-05-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_smslog_message_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='message_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
